version: 2.1

orbs:
  slack: circleci/slack@4.4.2

jobs:

 # FRONTEND    

  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            sudo webpack --mode development --progress
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "Failure during frontend build",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: fail
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build     

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:  
          keys: [frontend-build]
      - run:
          name: Test frontend
          command: |
            cd frontend
            sudo npm install --global jest
            sudo jest

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Scan for vulnerabilities for frontend
          command: |
            cd frontend
            npm i
            sudo npm audit fix --audit-level=critical --force

# BACKEND

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd backend
             sudo npm i
             sudo npm install typescript -g
             sudo tsc
      - slack/notify:
          event: fail
          mentions: '@shayunited21'
          template: basic_fail_1
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Test backend
          command: |
            cd backend
            sudo npm install --global jest
            sudo jest --runInBand

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Scan for vulnerabilities for backend
          command: |
            cd backend
            sudo npm audit fix --audit-level=critical --force
  
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            - build-frontend
      - test-backend:
          requires:
            - build-backend
      - scan-frontend:
          requires:
            - test-frontend
      - scan-backend:
          requires:
            - test-backend
        
     