version: 2.1

orbs:
  slack: circleci/slack@4.4.2

commands:
  notify_on_slack:
    steps:
      - slack/notify:
          event: fail
          mentions: '@shayunited21'
          template: basic_fail_1
  destroy_environment:
    steps:
      - run:
          name: Destroy env
          when: on_fail
          command: |
            aws s3 rm s3://udapeople1-9871051234349703 --recursive
            aws cloudformation delete-stack --stack-name frontend-stack-9871051234349703
            aws cloudformation delete-stack --stack-name backend-stack-9871051234349703

jobs:

 # FRONTEND    

  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          working_directory: ./frontend
          command: |
            npm i
            sudo npm install --global webpack
            sudo npm install --global webpack-cli
            sudo webpack --mode development --progress
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build     
      - notify_on_slack

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:  
          keys: [frontend-build]
      - run:
          name: Test frontend
          working_directory: ./frontend
          command: |
            sudo npm install --global jest
            sudo jest
      - notify_on_slack

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Scan for vulnerabilities for frontend
          working_directory: ./frontend
          command: |
            npm i
            sudo npm audit fix --audit-level=critical --force
      - notify_on_slack

# BACKEND

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          working_directory: ./backend
          command: |
             sudo npm i
             sudo npm install typescript -g
             sudo tsc
      - persist_to_workspace:
          root: ./backend
          paths:
            - dist
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - notify_on_slack

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Test backend
          working_directory: ./backend
          command: |
            sudo npm install --global jest
            sudo jest --runInBand
      - notify_on_slack

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Scan for vulnerabilities for backend
          working_directory: ./backend
          command: |
            sudo npm audit fix --audit-level=critical --force
      - notify_on_slack

# INFRA

  deploy-infrastructure:
    docker:
      - image: cimg/node:16.6.0
    steps:
      - checkout
      - run:
          name: Install AWS CLI dependencies
          command: |
            sudo apt-get update && sudo apt-get install -yy less
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            mkdir /tmp/workspace
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=project-9871051234349703 \
              --stack-name backend-stack-9871051234349703 \
              --parameter-overrides ID=9871051234349703
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=project-9871051234349703 \
              --stack-name frontend-stack-9871051234349703 \
              --parameter-overrides ID=9871051234349703
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            backend_ip=$(aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --output text)

            echo "$backend_ip" >> .circleci/ansible/inventory.txt

            curl -H "Content-Type: text/plain" -H "token: 6fba3369-5f48-48a3-af00-1f792a55da7e" --request PUT --data "$backend_ip" https://api.memstash.io/values/backend_ip
      - persist_to_workspace:
          root: .circleci/ansible/
          paths:
            - inventory.txt
      - notify_on_slack
      - destroy_environment

# DEPLOY PHASE

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "0c:c8:86:0a:a8:63:2c:f2:29:72:bd:69:b4:7e:29:3a"
      - attach_workspace:
          at: /tmp/
      - run:
          name: Install dependencies
          command: |
            apk update
            apk upgrade
            apk add --update ansible
      - run:
          name: Configure server
          working_directory: .circleci/ansible/configure-server
          command: |
            ansible-playbook configure-server.yml -i /tmp/inventory.txt
      - notify_on_slack    
      - destroy_environment

  run-migrations:
    docker:
      - image: cimg/node:16.6.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Install AWS CLI dependencies
          command: |
            sudo apt-get update && sudo apt-get install -yy less
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Run migrations
          working_directory: ./backend
          command: |
            set -ex
            touch migration-log
            echo ${CIRCLE_WORKFLOW_ID}
            npm run migrations > migration-log
            cat migration-log

      - run:
          name: Send migration results to memstash
          command: |
            set -ex
            if grep -q "has been executed successfully" migration-log
            then
              curl -H "Content-Type: text/plain" -H "token: 6fba3369-5f48-48a3-af00-1f792a55da7e" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
            fi
      - notify_on_slack
      - destroy_environment

  deploy-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:  
          keys: [frontend-build]
      - run:
          name: Install AWS CLI dependencies
          command: |
            sudo apt-get update && sudo apt-get install -yy less
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Install dependencies
          working_directory: ./frontend
          command: |
            set -ex
            sudo npm install --global webpack
            sudo npm install --global webpack-cli
            sudo webpack --mode development --progress
      - attach_workspace:
          at: /tmp/
      - run:
          name: Get backend url
          working_directory: ./frontend
          command: |
            export BACKEND_IP=$(curl -H "token: 6fba3369-5f48-48a3-af00-1f792a55da7e" --request GET https://api.memstash.io/values/backend_ip)
            export API_URL="http://${BACKEND_IP}:3030"
            echo "${API_URL}"
      - run:
          name: Deploy frontend objects
          working_directory: ./frontend
          command: |
             set -ex
             npm run build
             sudo chmod -R 777 ./dist
             aws s3 cp  ./dist s3://udapeople1-9871051234349703 --recursive
      - notify_on_slack     
      - destroy_environment

  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - add_ssh_keys:
          fingerprints:
            - "0c:c8:86:0a:a8:63:2c:f2:29:72:bd:69:b4:7e:29:3a"
      - attach_workspace:
          at: /tmp/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible curl rsync openssh nodejs npm
            ansible --version
            pip3 install --upgrade pip
            pip3 install awscli
            aws --version

      - run:
          name: Deploy backend
          working_directory: .circleci/ansible/deploy-backend
          command: |
            set -ex
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook deploy-backend.yml -i /tmp/inventory.txt
      - notify_on_slack
      - destroy_environment

  
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          # filters:
          #   branches:
          #     only: [test-feature-branch]
      - configure-infrastructure:
          requires: [deploy-infrastructure]
      - run-migrations:
          requires: [configure-infrastructure]
      - deploy-backend:
          requires: [run-migrations]
      - deploy-frontend:
          requires: [deploy-backend]
      # - smoke-test:
      #     requires: [deploy-backend, deploy-frontend]
      # - cloudfront-update:
      #     requires: [smoke-test]
      # - cleanup:
      #     requires: [cloudfront-update]
        
     