---

- name: "update apt packages."
  become: yes
  command: |
    apt update_cache
    echo "task 5 done"
    
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-prod.c5vtgmprr1t6.us-east-2.rds.amazonaws.com
    TYPEORM_PORT: 5532
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: udapeople123
    TYPEORM_DATABASE: udapeople-prod
  
- name: "upgrade packages"
  become: yes
  command: |
    apt upgrade
    echo "task 6 done"

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "run app using pm2"
  become: yes
  command: "sudo env PATH=$PATH:/usr/local/bin pm2 startup"


