---

- name: "set environment variables."
  become: yes
  command: |
    pwd
    
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-prod.c5vtgmprr1t6.us-east-2.rds.amazonaws.com
    TYPEORM_PORT: 5532
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: udapeople123
    TYPEORM_DATABASE: udapeople-prod

- name: remove dependencies that are no longer required
  become: yes
  command: |
    apt autoremove

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


