- name: "set environment variables."
  become: yes
  command: |
    echo "$playbook_dir"

- name: "Copy backend files"
  become: yes
  ansible.builtin.copy:
    src: /root/project/.circleci/backend/dist/
    dest: $HOME