

- name: "Copy backend files"
  ansible.builtin.copy:
    src: /tmp/dist/
    dest: $HOME

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "run app using pm2"
  command: |
    npm install
    npm run build
    pm2 stop default
    pm2 start npm -- start
