- name: Disable IPv6 with sysctl
  become: true 
  sysctl: name={{ item }} value=1 state=present reload=yes 
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: "Copy backend files"
  ansible.builtin.copy:
    src: /tmp/dist/
    dest: $HOME

- name: "run app using pm2"
  command: |
    npm install -g n 
    npm i
    npm run build
    pm2 start npm --name backend -- run start
    pm2 start main.js