- name: "Copy backend files"
  ansible.builtin.copy:
    src: /tmp/dist/
    dest: $HOME

- name: Install Node Modules
  command: |
    npm i
    npm run build

- name: "run app using pm2"
  command: |
    pm2 start npm run start:prod