---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:

    - name: "install python for Ansible."
      # Your code here
      shell: |
        set -ex
        touch esy
        sudo apt update
        echo task 1 done >> esy
        sudo apt install python3.8
        echo task 4 done >> esy
        python --version >> esy
       

  roles:
    - configuration-server