---

- name: "configuration play." 
  hosts: all
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: "install python for Ansible."
      shell: |
        set -ex
        if ! [ -x "$(command -v python3.8)" ]; then
          sudo apt install python3.8
        fi

  roles:
    - configuration-server