---

- name: "configuration play." 
  hosts: all
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: "install python for Ansible."
      shell: |
        set -ex
        if ! [ -x "$(command -v python3.8)" ]; then
          sudo apt install python3.8
        fi
       

  roles:
    - configuration-server

  environment:
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-prod.c5vtgmprr1t6.us-east-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: udapeople123
    TYPEORM_DATABASE: postgres
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_MIGRATIONS_DIR: ./src/migrations